<a href="https://colab.research.google.com/github/dilanHewawitharana/Intro-to-Deep-Learning-with-PyTorch/blob/master/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1Tlw_dv0alYUYx-8HQYwHqX54V6aiXPN6')

# Basic PyTorch tensor operations

An short introduction about PyTorch and about the chosen functions. 

- TORCH.LINSPACE
- TORCH.EYE
- TORCH.FULL
- TORCH.CAT
- TORCH.LOGSPACE

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.linspace

Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end

In [ ]:
# Example 1 - working
torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

Creates a one-dimensional tensor of size steps whose values are evenly spaced from 3 to 10

In [ ]:
# Example 2 - working
torch.linspace(-10, 10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

Creates a one-dimensional tensor of size steps whose values are evenly spaced from -10 to 10

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.linspace(-10, 20, steps=-5)

RuntimeError: ignored

steps always should be positive

Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/dilanhewawitharana/01-tensor-operations


'https://jovian.ai/dilanhewawitharana/01-tensor-operations'

## Function 2 - torch.eye

Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

In [ ]:
# Example 1 - working
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

1 apears in the diagonal and zeros are exist in other places

In [ ]:
# Example 2 - working
torch.eye(3, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

we can specify the number of columns in the second arg. but the output will be as in above example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.eye(-3)

RuntimeError: ignored

number of row must be greater or equal to 0

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/dilanhewawitharana/01-tensor-operations


'https://jovian.ai/dilanhewawitharana/01-tensor-operations'

## Function 3 - torch.full

Creates a tensor of size size filled with fill_value

In [ ]:
# Example 1 - working
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

created (2,3) vector tensor and filled with 3.1416 value

In [ ]:
# Example 2 - working
torch.full((2, 3), 3.141592, requires_grad=True)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]], requires_grad=True)

If we need to calculate gradient of this vector tensor, we can pass additional argd called 'requires_grad=True'

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.full((2, 3.), 3.141592)

TypeError: ignored

argument 'size' must be tuple of ints

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/dilanhewawitharana/01-tensor-operations


'https://jovian.ai/dilanhewawitharana/01-tensor-operations'

## Function 4 - torch.cat

Concatenates the given sequence of seq tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [ ]:
# Example 1 - working
t1 = torch.ones(2, 3)
t2 = t1 * 2
t3 = t1 * 3
torch.cat((t1, t2, t3), 0)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [3., 3., 3.],
        [3., 3., 3.]])

Concatenates the given sequence of seq tensors in horizontal

In [ ]:
# Example 2 - working
torch.cat((t1, t2, t3), 1)

tensor([[1., 1., 1., 2., 2., 2., 3., 3., 3.],
        [1., 1., 1., 2., 2., 2., 3., 3., 3.]])

Concatenates the given sequence of seq tensors in verticaly

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
T1 = torch.ones(3, 2)
torch.cat((t1, T1), 0)

RuntimeError: ignored

All tensors must either have the same shape (except in the concatenating dimension) or be empty.

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/dilanhewawitharana/01-tensor-operations


'https://jovian.ai/dilanhewawitharana/01-tensor-operations'

## Function 5 - torch.logspace

Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end on a logarithmic scale.

In [ ]:
# Example 1 - working
torch.logspace(start=-10, end=10, steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

Creates a one-dimensional tensor of size steps whose values are evenly spaced from -10 to 10 on a logarithmic scale.

In [ ]:
# Example 2 - working
torch.logspace(start=0, end=20, steps=5, base=2)

tensor([1.0000e+00, 3.2000e+01, 1.0240e+03, 3.2768e+04, 1.0486e+06])

Creates a one-dimensional tensor of size steps whose values are evenly spaced from 0 to 20 on a logarithmic scale with base 2.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.logspace(start=0, end=20, steps=-5)

RuntimeError: ignored

number of steps must be non-negative

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/dilanhewawitharana/01-tensor-operations


'https://jovian.ai/dilanhewawitharana/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/dilanhewawitharana/01-tensor-operations


'https://jovian.ai/dilanhewawitharana/01-tensor-operations'